
source "https://rubygems.org"

gem 'sinatra', git: 'https://github.com/juanpastas/sinatra.git'
gem 'sinatra-contrib', git: 'https://github.com/sinatra/sinatra-contrib.git'
gem "mixlib-config"
gem "sinatra-content-for2"
